- name: POST F5 ATC Declaration
  hosts: bigips
  gather_facts: false
  tasks:
    - name: F5 ATC POST
      include_role:
        name: /home/danielt/ansible/ansible-role-f5_atc_deploy_declaration
      vars:
        atc_method: POST
        atc_declaration_file: "/home/danielt/ansible/f5-automation/as3/3.1_role_with_static_json/simple_http_app.as3.json"
        atc_delay: 10
        atc_retries: 5
        ## as3_tenant: TENANT_NAME (limits scope to specified tenant)
        #as3_tenant: Sample_01

        provider:
          server: 10.10.102.1
          #server_port: "443"
          user: admin
          password: admin
          validate_certs: "false"
          #auth_provider: tmos

    ## atc_AS3_status, atc_DO_status, or atc_TS_status
    - name: Output declaration status
      debug:
        var: atc_AS3_status