- name: POST AT Declaration
  hosts: bigip

  tasks:

    - name: ATC POST
      include_role:
        name: atc_deploy
      vars:
        atc_method: POST
        atc_declaration: "{{ lookup('template', 'decl.json') }}"
        # atc_declaration_file: files/as3.json
        # atc_declaration_url: "https://testurl/as3.json"
        atc_declaration_file: "files/as3.json"
        atc_delay: 10
        atc_retries: 5
        provider:
          server: 10.10.102.1
          server_port: "443"
          user: admin
          password: admin
          validate_certs: "false"
          auth_provider: tmos

    # atc_AS3_status, atc_DO_status , atc_TS_status
    - debug: var=atc_AS3_status