---
- name: Using AS3 to deploy a configuration
  hosts: bigip102
  gather_facts: False
  vars:
    provider:
      password: "{{ bigip_password }}"
      server: "{{ ansible_host }}"
      user: "{{ bigip_username }}"
      validate_certs: False
 
  tasks:
    - name: Deploy a simple HTTP application
      bigip_appsvcs_extension:
        content: "{{ lookup('file', 'simple_http_app.as3.json') }}"
        state: present
        provider: "{{ provider }}"
      delegate_to: localhost