- name: GET AT Declaration
  hosts: bigip

  tasks:

    - name: ATC GET
      include_role:
        name: atc_deploy
      vars:
        atc_method: GET
        # Select the service as AS3, Device, or Telemetry
        atc_service: AS3
        provider:
          server: 192.168.1.245
          server_port: "443"
          user: admin
          password: admin
          validate_certs: "false"
          auth_provider: tmos

- debug: var=atc_GET_status